learning_rate: 0.0003
gamma: 0.99
epsilon: 0.2
num_epochs: 10
batch_size: 64
clip_range: 0.2
value_loss_coef: 0.5
entropy_coef: 0.01
max_grad_norm: 0.5
log_interval: 10
save_interval: 5
model_path: "models/ppo_model"